### PR TITLE
refactor!: remove python2

### PR DESCRIPTION
**Pull request by kuwv**
Python 2 has been deprecated for over a year now. This pull request removes integrations with invoke with six that are used to support now deprecated Python2 compatibility. Removing this will allow builds to be more simplified while allow integration with more modern tooling from the Python ecosystem.

see corresonding: https://github.com/pyinvoke/invocations/pull/30

### CODE REVIEW

**Comment by kuwv** [comment]
Tests need to be run with corresponding invocations with six removed.

**Comment by neozenith** [comment]
@kuwv Thanks for openning this, but @bitprophet is actively working on removing Python 2 (after a long time of dealing with other priorities than FOSS).

The migration of invoke, fabric and paramiko from Travis to CircleCI was a blocker which is now complete.

He is working on removing Python 2 from invoke first since it has least dependencies and Fabric and paramiko depend on Invoke.

**Comment by bitprophet** [comment]
What @neozenith said, though so far I've started in Invocations myself (I think before that PR over there was filed). So you may want to just close that one (I have a branch already with most of those types of changes applied), but I'll make a note to build off this one when I turn my attention to Invoke-proper.

As with any PR, I may end up using a scalpel, but especially for this kind of more grunt-work it'll save me a lot of time regardless, so thank you!

**Comment by kuwv** [comment]
@bitprophet, @neozenith, glad this will be useful then. I'll close the invocations PR.

**Comment by kuwv** [comment]
One caveat, I updated to pep517 build using setuptools.

**Comment by kuwv** [comment]
@neozenith Do you need me to refresh this? Or, do you have a time frame?

**Comment by bitprophet** [comment]
Gonna take a crack at applying this now and hope it saves me some time! 🙏🏻  Invoke is now up on my Py2 chopping block.

**Comment by bitprophet** [comment]
Rebased onto latest main, made some minor changes, and merged back into main. I'll take the rest from here - thanks! 🙌🏻

**Comment by kuwv** [comment]
Huzzah!!!

**Pull request closed without merging**
