### PR TITLE
Make Context.cd() accept Path objects

### LINKED ISSUE #454: Accept pathlib.Path object in Context.cd
Allow the path parameter to be a `pathlib.Path` instance as well as a string parameter.  As a convenience as `pathlib.Path` are used more and more for path handling.  Thanks.

### LINKED ISSUE #577: Strange Issue with ctx.cd (possibly within my env?)
Hey, loving the library so far. Very handy and all it's missing to me is make-like dependency refresh recognition, which I might get around to working on eventually if there's any interest.

~Had a script that was working, then stopped working after I poked around reading the source. Here's the traceback~
```
Traceback (most recent call last):
  File "/spare/local/hflinner/venv-infra/bin/invoke", line 11, in <module>
	sys.exit(program.run())
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/program.py", line 363, in run
	self.execute()
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/program.py", line 532, in execute
	executor.execute(*self.tasks)
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/executor.py", line 129, in execute
	result = call.task(*args, **call.kwargs)
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/tasks.py", line 128, in call
	result = self.body(*args, **kwargs)
  File "/spare/local/hflinner/invoke/myproj/tools/tests/tasks.py", line 23, in build1
	ctx.run(release_cmd)
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/context.py", line 94, in run
	return self._run(runner, command, **kwargs)
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/context.py", line 100, in _run
	command = self._prefix_commands(command)Had a script that was working, then stopped working after I poked around reading 
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/context.py", line 242, in _prefix_commands
	current_directory = self.cwd
  File "/spare/local/hflinner/venv-infra/lib/python2.7/site-packages/invoke/config.py", line 125, in getattr
	raise AttributeError(err)
AttributeError: No attribute or config key found for 'cwd'

Valid keys: ['Path', 'debug', 'find_config', 'find_here', 'lazy', 'listen', 'log_dir', 'make',  'market', 'mytarget', 'run', 'runners', 'server', 'set_paths', 'sudo', 'super_repo_root', 'task', 'tasks', 'workspace']

Valid real attributes: ['cd', 'clear', 'config', 'cwd', 'from_data', 'pop', 'popitem', 'prefix', 'run', 'setdefault', 'sudo', 'update']
```
Notice that the error is that cwd isn't found but cwd is a valid real attribute. ~This happened after I poked around in the source a bit, so I suspected it was my fault for accidentally changing something. So I rm -rf invoke* 'd in my site-packages directory and reinstalled, but the problem persists.~ There's nothing that seems suspicious to me in my config. I'm executing `invoke build1 mytarget` where build1 looks like this
```
@task
def build1(ctx, target):
   logging.info("Releasing {} to {}"
                .format(target, ctx.make.release_dir))
   cfg = ctx[target]
   with ctx.cd(ctx.server.repo_root):
       print(ctx)
       ctx.run(release_cmd)
```
Where the traceback is erroring out on the `ctx.run`. Adding a `cwd` field to my invoke.py "fixes" the issue. But this function used to work!

**Note**: Fixed my error, turned out to be something that I think could be handled better?
`with ctx.cd(str(ctx.server.repo_root)):`
Where repo_root is a pathlib2 Path obj, not a string (my invoke.py is somewhat large and involved).

### LINKED ISSUE #658: Path arguments must be passed to os.fspath()
Take the following task:

```py
from pathlib import Path
from invoke import task


@task
def cd(ctx, path):
    with ctx.cd(Path(path)):
        ctx.run(f"echo {path}")
```

`invoke` will fail with the following obscure error:

```console
$ inv cd .
Traceback (most recent call last):
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/config.py", line 111, in __getattr__
    return self._get(key)
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/config.py", line 167, in __getitem__
    return self._get(key)
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/config.py", line 176, in _get
    value = self._config[key]
KeyError: 'cwd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/share/virtualenvs/inv-Li_05Nqg/bin/inv", line 10, in <module>
    sys.exit(program.run())
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/program.py", line 384, in run
    self.execute()
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/program.py", line 566, in execute
    executor.execute(*self.tasks)
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/executor.py", line 129, in execute
    result = call.task(*args, **call.kwargs)
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/tasks.py", line 127, in __call__
    result = self.body(*args, **kwargs)
  File "/home/spack/workspace/py/inv/tasks.py", line 8, in cd
    ctx.run(f"echo {path}")
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/context.py", line 94, in run
    return self._run(runner, command, **kwargs)
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/context.py", line 100, in _run
    command = self._prefix_commands(command)
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/context.py", line 242, in _prefix_commands
    current_directory = self.cwd
  File "/share/virtualenvs/inv-Li_05Nqg/lib/python3.7/site-packages/invoke/config.py", line 123, in __getattr__
    raise AttributeError(err)
AttributeError: No attribute or config key found for 'cwd'

Valid keys: ['run', 'runners', 'sudo', 'tasks', 'timeouts']

Valid real attributes: ['cd', 'clear', 'config', 'cwd', 'from_data', 'pop', 'popitem', 'prefix', 'run', 'setdefault', 'sudo', 'update']
```

This is due to `invoke.context.Context.cd` adding any given path directly to `command_cwds` and `invoke.context.Context.cwd` treating any value in there as a string.

Since Python 3.6, any object can represent a path by implementing the [`__fspath__()`](https://docs.python.org/3/library/os.html?#os.PathLike.__fspath__) abstract method.

Since then, when dealing with any path object, it is now required to call [`os.fspath()`](https://docs.python.org/3/library/os.html?#os.fspath) in order to get the `str` or `bytes` representation of the path.

### PR DESCRIPTION
**Pull request by florisla**
This is a rebase (with minor modifications) of #583.

The original 583 stalled on AppVeyor, but that is disabled now so this should pass CI.

Closes #583 - original PR
Closes #681 - more recent but similar PR
Fixes #454 - original issue
Fixes #577 - duplicate issue
Fixes #658 - duplicate issue

### CODE REVIEW

**Comment by skycaptain** [comment]
Any news on this PR?  Run into #577 today.

**Comment by florisla** [comment]
Rebased on master.

**Comment by russkel** [comment]
Would be really nice to get this merged.

**Comment by bitprophet** [comment]
Out in 1.5!

**Comment by russkel** [comment]
How is it that the PR says it was merged, yet only commits authored by @bitprophet appear in the git log? Is this a feature of github?

**Comment by florisla** [comment]
Hi,

Are you referring to the 'network' view on GitHub?

That's probably due to the changes being merged into an integration branch
first (named 607-int).

So for the master branch, what's being merged is 607-int, not directly
florisla:454-context-cd-with-path-object
<https://github.com/florisla/invoke/tree/454-context-cd-with-path-object> .

But if you follow the merge commit, you'll still find the original commits.

https://github.com/pyinvoke/invoke/commit/54b28be2c094c5dafccd5adaee8196e3ae6f2614

This commit has two parents.

Regards
Floris

Op do 31 dec. 2020 06:48 schreef Russ <notifications@github.com>:

**Comment by russkel** [comment]
Hi @florisla. Thanks, I worked this out soon after I posted it and deleted the comment. Thanks regardless.

**Pull request merged**
