### PR TITLE
Give the process a chance to terminate correctly

### PR DESCRIPTION
**Pull request by flazzarini**
Should fix the issue described in #660

### CODE REVIEW

**Comment by florisla** [comment]
The CI build fails because `Popen.wait()` does not have a `timeout` argument in Python 2.7.

See https://docs.python.org/2/library/subprocess.html#subprocess.Popen.wait

Would it be dangerous to simply call `wait()` in case of python <3 ?

**Comment by flazzarini** [comment]
Yes I didn't think of python 2 support at all, but as python 2 is end of life on 01.01.2020 will you also drop support for it in the invoke library? If this is the case this fix could applied on a python3 only branch.

**Comment by ralphie0112358** [comment]
I'd love to have this merged and released!  Any updates???

**Comment by gbansaghi** [comment]
I would argue that `wait()` with no timeout would be the correct approach. In practice, 3 seconds should be enough, but the library shouldn't rely on such an arbitrary timeout value (what if it's run on a _very_ old machine, what if there's really heavy I/O, etc.)

**Comment by bitprophet** [comment]
Thanks for this & the additional reports!

I can't drop Python 2 just yet, and I'm also just uncomfortable with a timeout-driven solution, I'd rather attempt to identify the race condition in play & solve it with a threading event or similar; so I'm probably going to supply my own patch instead of merging this directly (tho I reserve the right to backpedal furiously if that goes nowhere 😂 ). Please follow #660 for details.

**Pull request closed without merging**
