### PR TITLE
Build improvements

### PR DESCRIPTION
**Pull request by thedrow**
Added PyPy3 to the build, moved to container based infrastructure and enabled pip caching.

### CODE REVIEW

**Comment by thedrow** [comment]
Can you explain why the build fails so I can fix it?
Is it because PyPy3 is an implementation of Python 3.2?

**Comment by bitprophet** [comment]
Thanks for this! The issue must be that our (travis.yml) test to skip doc-builds on 3.2 (Sphinx doesn't support it) isn't correctly triggering on PyPy3, I bet `TRAVIS_PYTHON_VERSION` isn't being set to `"3.2"` in that case (guessing "PYPY" is in there somewhere, or...something?)

Compare https://travis-ci.org/pyinvoke/invoke/jobs/72795107#L5996 to https://travis-ci.org/pyinvoke/invoke/jobs/72795111#L1027 - "real" Python 3.2 correctly skips the docs build step, but PyPy3 does not.

I don't see the build output stating what that value is, you'll want to make some test commits adding things like `- echo TRAVIS_PYTHON_VERSION: '$TRAVIS_PYTHON_VERSION'` or whatnot, so we can see what the value is.

**Comment by bitprophet** [comment]
FTR we nixed 3.2 recently so that should be moot now. I merged and we'll see if Travis likes the sum total of the changes soon...

**Comment by bitprophet** [comment]
OK, as semi-expected, PyPy3 fails because of Sphinx, but passes everything else: https://travis-ci.org/pyinvoke/invoke/jobs/102019458

**Pull request merged**
