### PR TITLE
added --shortlist flag, primarily for driving zsh completion

### PR DESCRIPTION
**Pull request by aroberts**

### CODE REVIEW

**Comment by IvanMalison** [comment]
@wo0dyn I just set up zsh completion for myself without this branch

check it out at https://github.com/IvanMalison/dotfiles/blob/master/dotfiles/lib/completions/_invoke

**Comment by IvanMalison** [comment]
Whats the status of this pull request?

**Comment by wo0dyn** [comment]
@Ivan

**Comment by bitprophet** [comment]
Going to roll this into #104, want to have a more holistic set of completion options. Will still credit in changelog tho :) thanks!

**Pull request closed without merging**
