### PR TITLE
refactor: replace imp with importlib

### PR DESCRIPTION
**Pull request by kuwv**
@bitprophet This is mostly there. Just need to sort the issues with `program`.

### CODE REVIEW

**Comment by kuwv** [comment]
@bitprophet looks like I got the tests working. Need to remove `import_module` and this should be ready to go. Can you confirm if this looks fine or not?

**Comment by kuwv** [comment]
@bitprophet alright `importlib` is passing. Ready for review!

**Comment by kuwv** [comment]
#675 
#829

**Comment by kuwv** [comment]
I have additional changes to remove the parent path from 'load()' and retrieve it from the module. But that's something that could have been done before so...

**Comment by joerg-tt** [comment]
Great! Hope this gets merged soon.

**Comment by kuwv** [comment]
@jefftriplett could you give this a review?

**Comment by kuwv** [comment]
@bitprophet ping

**Comment by bitprophet** [comment]
I'll try to find the time to review this in depth next time I'm doing Invoke-y things. Pairs well with the typing update that is yet unreleased, I'd prob pop both out as a 'support' minor version bump when I do this. thanks! 🙏🏻

**Comment by kuwv** [comment]
Great to see you back.

For the release... there's one caveat, I removed decorator.py because it wasn't used but then realized it's being consumed by fabric.

**Comment by bitprophet** [comment]
Thrusting my head above the surface of the Paramiko swamp for a gasp of air & to actually look at this 🙏🏻  unless something drastic happens I'll try to pop out invoke 2.1 today with this plus all of your other recent work!

**Comment by bitprophet** [comment]
Rebased onto an unrelated fix so now github's behind the times, but this is merged and on pypi! thanks again 🙏🏻

**Pull request closed without merging**
