### PR TITLE
Add fish completion script

### PR DESCRIPTION
**Pull request by jaimeMF**

### CODE REVIEW

**Comment by bitprophet** [comment]
Sweet, thanks!

**Comment by jaimeMF** [comment]
Thanks!
Could you change my name in the changelog to `Jaime Marquínez Ferrándiz`?, `Marquínez` is my first surname (in Spain we use two surnames, [wikipedia article](https://en.wikipedia.org/wiki/Spanish_naming_customs))

**Comment by bitprophet** [comment]
I'd been wondering why so many contributors with Spanish-sounding names always had their "middle" name listed! Sorry about that.

**Comment by jaimeMF** [comment]
I would also get confused, thanks for the fix.

**Pull request merged**
