### PR TITLE
[sudo] This small update fix so many situations ...

### PR DESCRIPTION
**Pull request by albundy83**

### CODE REVIEW

**Comment by albundy83** [comment]
Could be done with:
```python
cmd_str = "sudo -S -p '{}' {} sh -c \"{}\"".format(prompt, user_flags, command)
```

**Comment by Varriount** [comment]
This assumes `bash` is present on the system (which it might not be!).

**Comment by albundy83** [comment]
Yes you are rigth but sudo command is limited, that's a pity :(

**Comment by neozenith** [comment]
Is there an issue with passing `bash -c "yourcommand"` or `sh -c "yourcommand"` as the command  to the original code here?

**Pull request closed without merging**
