### PR TITLE
Remove unused Appveyor configuration

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

### CODE REVIEW

**Comment by gliptak** [comment]
@bitprophet please review

**Comment by bitprophet** [comment]
Appveyor still seems to exist and I'm able to log in there, though it's not clear to me why it stopped building a few years ago. All else equal I wouldn't mind having them run our tests on occasion. Did something change on their end that makes them unsuitable for OSS projects?

**Comment by gliptak** [comment]
I'm not aware if or what changed with AppVeyor. Based on a quick review, external build services are constraining parallel builds, some requiring to login to see build logs and moving into a "credit" system for OSS projects,

https://www.appveyor.com/pricing/
https://travis-ci.com/account/plan?billingStep=1
https://circleci.com/pricing/index.html

As Github Actions extends OSs supported

https://docs.github.com/en/free-pro-team@latest/actions/reference/specifications-for-github-hosted-runners#supported-runners-and-hardware-resources

and more and more Actions are published, it might be a preferable build tool.

**Comment by bitprophet** [comment]
I'm -0 on GHA as I'm not terrifically happy with some of how Github has been under Microsoft (not least their willingness to work with USA's ICE) and generally just not a big fan of putting more eggs in their one basket.

I've been looking at Circle for the primary (Linux) build (they offer a decent number of credits for OSS projects). Seems they offer Windows, so depending on how much of the OSS credits we end up burning for Linux, I'd certainly consider merging support for their Windows workers.

**Pull request closed without merging**
