### PR TITLE
Use inspect.signature to enable Python 3 only features when defining tasks

### LINKED ISSUE #372: Allow invoke to run tasks with type hinting
Issue #248 mentions type hinting, but I think that is for Invoke to use type hinting internally. This issue is to allow Invoke to run tasks with type hinting annotations.

With current master, when defining a task like this:

```
@task
def hello(name: str = 'Anonymous'):
    print('Hello, {name}!'.format(name=name))
```

I get the following error message when trying to run this task:

> ValueError: Function has keyword-only arguments or annotations, use getfullargspec() API which can support them

I followed the advice and replaced getargspec() in tasks.py with getfullargspec() and everything seems to work.

I don''t know the full implications of this change, but I'll create a fork and run the tests and see if something breaks.

### PR DESCRIPTION
**Pull request by rsxm**
Fix  #372

### CODE REVIEW

**Comment by jr-minnaar** [comment]
Locally all tests have passed when running

**Comment by bitprophet** [comment]
Linking this to #357. @jr-minnaar: a) thanks! b) if you can, please check the assertion made in #357 about how there might be even more to this than simple getargspec/getfullargspec - it'd be nice for this to degrade gracefully as much as possible, so if there's things even newer/"better" than getfullargspec, it'd be rad to use them if it makes sense. (So e.g. inspect.signature -> not there? getfullargspec -> also not there? getargspec)

**Comment by jr-minnaar** [comment]
Thanks, I'll have a look at #357. Do I leave this pull request open while investigating or what is the protocol?

**Comment by bitprophet** [comment]
Leaving this open is fine, I assume you'd just push more commits once you finish looking into that stuff. Thanks!

**Comment by jr-minnaar** [comment]
I've updated the pull request to now use inspect.signature instead of inspect.getargspec.

I've also addressed one of the TODO's that related to the argspec method. Let me know if I should rather take that out of this pull request.

**Comment by bitprophet** [comment]
If you have a sec can you write out a list of which Python versions have which of `getargspec`, `getfullargspec`, `signature`, etc? I'd like to make sure we're not leaving e.g. Python 3.3 or 2.6 or whatever, out in the cold here.

If "just" both of `getargspec` and `signature` covers all of 2.6, 2.7, 3.3, 3.4, 3.5+...that'd be fine :) (We no longer bother with 3.2 so maybe that's where some of the earlier confusion came in.)

**Comment by jr-minnaar** [comment]
> If "just" both of getargspec and signature covers all of 2.6, 2.7, 3.3, 3.4, 3.5+...that'd be fine :) (We no longer bother with 3.2 so maybe that's where some of the earlier confusion came in.)

That indeed seems to be the case:

| Python 2 | getargspec | getfullargspec | signature |
|----------|-------------|---------------|-----------|
| 2.6       | ✅ Changed | ❌ No | ❌ No |
| 2.7       | ✅ Yes | ❌ No | ❌ No |

| Python 3 | getargspec | getfullargspec | signature |
|----------|-------------|---------------|-----------|
| 3.2       | ⚠️ Deprecated | ✅ Yes | ❌ No |
| 3.3       | ⚠️ Deprecated | ✅ Yes | ✅ New |
| 3.4       | ⚠️ Deprecated | ✅ Changed | ✅ Yes |
| 3.5       | ⚠️ Deprecated | ⚠️ Deprecated | ✅ Yes |
| 3.6       | ⚠️ Deprecated | ⚠️ Deprecated | ✅ Yes |

**Comment by bitprophet** [comment]
Awesomesauce, thanks! Also excellent use of emoji ❤️

**Comment by jr-minnaar** [comment]
Hi @bitprophet

I see you've moved this pull request to the 0.16 milestone. I've rebased and rerun tests. Also removed some extra changes not related to this issue.

Looking forward to the next release :-)

**Comment by FranklinChen** [comment]
I'm sad to see this wasn't fixed for the 1.0.0 release that just came out.

**Comment by haydenflinner** [comment]
There's actually an easier way than the PR for this commit gives, since `decorator` includes a similar thing to what this PR implements

```
commit 14c88f9b3bc7525df66a3d4ec2ad13a733e08bf1
Author: Hayden Flinner <haydenflinner@gmail.com>
Date:   Mon Nov 5 20:19:02 2018 -0500

    Fixed getfullargspec on Py2.

diff --git a/invoke/tasks.py b/invoke/tasks.py
index 7fa67025..79833b8f 100644
--- a/invoke/tasks.py
+++ b/invoke/tasks.py
@@ -8,7 +8,7 @@ from copy import deepcopy
 import inspect
 import types
 
-from .util import six
+from .util import six, getfullargspec
 
 if six.PY3:
     from itertools import zip_longest
@@ -156,7 +156,7 @@ class Task(object):
         # TODO: __call__ exhibits the 'self' arg; do we manually nix 1st result
         # in argspec, or is there a way to get the "really callable" spec?
         func = body if isinstance(body, types.FunctionType) else body.__call__
-        spec = inspect.getfullargspec(func)
+        spec = getfullargspec(func)
         arg_names = spec.args[:]
 
         # Collect into for regular args
diff --git a/invoke/util.py b/invoke/util.py
index a574580a..c70251c3 100644
--- a/invoke/util.py
+++ b/invoke/util.py
@@ -22,6 +22,7 @@ try:
     from .vendor.lexicon import Lexicon  # noqa
     from .vendor import six
     from .vendor.six.moves import reduce  # noqa
+    from .vendor.decorator import getfullargspec
 
     if six.PY3:
         from .vendor import yaml3 as yaml  # noqa
```

You can see it working [here](https://magicinvoke.readthedocs.io/en/latest/examples/make-replacement/README.html#make-replacement), I did it to use type-annotations for an invoke extension I worked on.

**Comment by dperetti** [comment]
Please 🙏

**Comment by bryzgaloff** [comment]
@bitprophet does anything stop this PR from being merged? @rsxm are you using some other workaround for that issue?

**Comment by jrabbit** [comment]
This is a priority for me, I can review or advocate or whatever we need to do to finish this?

**Comment by rsxm** [comment]
@bryzgaloff  hi, I still use my patched branch with this fix. I don't update this dependency much, so haven't looked at this in a long time.

**Comment by offbyone** [comment]
I can attest to this patch fixing my encounter with #357, at least.

**Comment by paambaati** [comment]
@bitprophet I noticed that you've been committing again recently. Would you mind reviewing this PR once again and merging?

**Comment by ktbarrett** [comment]
Jesus, this fix has been available for 6 years and no merge? @bitprophet you need to consider delegating maintenance of this library to someone else.

**Pull request closed without merging**
